# ========================
# Spring Boot Application
# ========================
spring.application.name=backend

# ========================
# Database - GroupCap
# ========================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/groupcap
#spring.datasource.url=jdbc:postgresql://groupcap-db.ca9mwokeg7no.us-east-1.rds.amazonaws.com:5432/groupcap
spring.datasource.username=groupcap
spring.datasource.password=24X2iCQFBnQXar06lJ6h

# ========================
# JPA / Hibernate - GroupCap
# ========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true